require "../painter/*"
require "../wm/*"
require "./core/*"
require "./widget/widget.cr"
require "./widget/window.cr"
require "./widget/windecoration.cr"
require "./widget/termbox.cr"
require "./data/*"
