#!/bin/bash

crystal_target=`echo $opt_arch | sed 's/-[^-]*$//g'`
script_path=$(dirname $(realpath $0))
basename=`basename $1 .cr`

if [[ "x$2" = "x" ]]; then
  echo "output argument required"
  exit 1
else
  output="$2"
fi

CRYSTAL_PATH="$script_path" \
  crystal build $1 -Ddebug_gc --error-trace --cross-compile --target $crystal_target --prelude prelude --release -Ddisable_overflow || exit $?
$opt_arch-gcc -O2 -o $output "$basename.o" $LDFLAGS || exit $?
rm "$basename.o"
exit 0
