#!/bin/sh

ARCH="i386-elf"
SCRIPT_PATH=$(dirname $(realpath $0))

basename=`basename $1 .cr`
if [[ "x$2" = "x" ]]; then
  echo "output argument required"
  exit 1
else
  output="$2"
fi

cleanup() {
  exit $1
}

CRYSTAL_PATH="$SCRIPT_PATH" \
  crystal build $1 --cross-compile --target $ARCH --prelude prelude --release || cleanup $?
$ARCH-lilith-gcc -o $output "$basename.o" || cleanup $?
rm "$basename.o"
cleanup 0
