# Generated by GCC with -O2

	.text
	.p2align 4
	.globl	kalpha_blend
	.type	kalpha_blend, @function
kalpha_blend:
.LFB5521:
	.cfi_startproc
	testq	%rdx, %rdx
	je	.L1
	movdqa	.LC0(%rip), %xmm8
	movdqa	.LC1(%rip), %xmm7
	salq	$4, %rdx
	xorl	%eax, %eax
	movdqa	.LC2(%rip), %xmm2
	movdqa	.LC3(%rip), %xmm6
	pxor	%xmm3, %xmm3
	movdqa	.LC4(%rip), %xmm4
	movdqa	.LC5(%rip), %xmm5
	.p2align 4,,10
	.p2align 3
.L3:
	movdqa	(%rsi,%rax), %xmm10
	movdqa	(%rdi,%rax), %xmm1
	movdqa	%xmm7, %xmm11
	movdqa	%xmm10, %xmm0
	pand	%xmm2, %xmm1
	pand	%xmm8, %xmm0
	psrldq	$3, %xmm0
	pshufhw	$10, %xmm0, %xmm0
	pshuflw	$160, %xmm0, %xmm0
	psubusb	%xmm0, %xmm11
	movdqa	%xmm10, %xmm0
	pand	%xmm4, %xmm10
	pmullw	%xmm11, %xmm1
	psrlw	$8, %xmm10
	pand	%xmm2, %xmm0
	psrlw	$8, %xmm1
	paddsw	%xmm6, %xmm1
	paddsw	%xmm0, %xmm1
	movdqa	(%rdi,%rax), %xmm0
	movdqa	%xmm1, %xmm9
	pand	%xmm4, %xmm0
	psrlw	$8, %xmm9
	psrlw	$8, %xmm0
	pcmpgtw	%xmm3, %xmm9
	pmullw	%xmm11, %xmm0
	por	%xmm9, %xmm1
	pand	%xmm2, %xmm1
	psrlw	$8, %xmm0
	paddsw	%xmm5, %xmm0
	paddsw	%xmm10, %xmm0
	movdqa	%xmm0, %xmm10
	psrlw	$8, %xmm10
	pcmpgtw	%xmm3, %xmm10
	por	%xmm10, %xmm0
	pand	%xmm2, %xmm0
	psllw	$8, %xmm0
	por	%xmm0, %xmm1
	movaps	%xmm1, (%rdi,%rax)
	addq	$16, %rax
	cmpq	%rax, %rdx
	jne	.L3
.L1:
	ret
	.cfi_endproc
.LFE5521:
	.size	kalpha_blend, .-kalpha_blend
	.section	.rodata.cst16,"aM",@progbits,16
	.align 16
.LC0:
	.quad	-72057589759737856
	.quad	-72057589759737856
	.align 16
.LC1:
	.byte	-1
	.byte	0
	.byte	-1
	.byte	0
	.byte	-1
	.byte	0
	.byte	-1
	.byte	0
	.byte	-1
	.byte	0
	.byte	-1
	.byte	0
	.byte	-1
	.byte	0
	.byte	-1
	.byte	0
	.align 16
.LC2:
	.quad	71777214294589695
	.quad	71777214294589695
	.align 16
.LC3:
	.value	1
	.value	1
	.value	1
	.value	1
	.value	1
	.value	1
	.value	1
	.value	1
	.align 16
.LC4:
	.quad	280375465148160
	.quad	280375465148160
	.align 16
.LC5:
	.value	1
	.value	0
	.value	1
	.value	0
	.value	1
	.value	0
	.value	1
	.value	0
	.ident	"GCC: (GNU) 9.1.0"
	.section	.note.GNU-stack,"",@progbits
